openapi: 3.0.2
components:
  paths:
    auth:
      get:
        summary: Request challenge for login
        tags:
          - Authentication
        operationId: "get_auth"
        description: |
          Request challenge for digest-access challenge-response authentication.

          The API may chose to reply with a valid session if no authentation is needed for this server.

          Note that challenges are only valid for a very short time, use them to immediately compute a response. There is no need to get a challenge before users have finished entering their passwords.
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: 'auth.yaml#/components/schemas/session'
                    - $ref: 'common.yaml#/components/schemas/took'
                examples:
                  login_okay:
                    $ref: 'auth.yaml#/components/examples/login_okay'
                  no_login_required:
                    $ref: 'auth.yaml#/components/examples/no_login_required'
                  login_required:
                    $ref: 'auth.yaml#/components/examples/login_required'
                  dns_failure:
                    $ref: 'auth.yaml#/components/examples/dns_failure'
      post:
        summary: Submit response for login
        tags:
          - Authentication
        operationId: "add_auth"
        description: |
          Submit computed response
        requestBody:
          description: Callback payload
          content:
            'application/json':
              schema:
                $ref: 'auth.yaml#/components/schemas/response'
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: 'auth.yaml#/components/schemas/session'
                    - $ref: 'common.yaml#/components/schemas/took'
                examples:
                  login_okay:
                    $ref: 'auth.yaml#/components/examples/login_okay'
                  no_login_required:
                    $ref: 'auth.yaml#/components/examples/no_login_required'
          '400':
            description: Bad Request
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: 'auth.yaml#/components/errors/bad_request'
                    - $ref: 'common.yaml#/components/schemas/took'
                examples:
                  no_payload:
                    $ref: 'auth.yaml#/components/examples/errors/no_payload'
                  no_response:
                    $ref: 'auth.yaml#/components/examples/errors/no_response'
                  response_inval:
                    $ref: 'auth.yaml#/components/examples/errors/response_inval'
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: 'common.yaml#/components/errors/unauthorized'
                    - $ref: 'common.yaml#/components/schemas/took'
      delete:
        summary: Delete session
        tags:
          - Authentication
        operationId: "delete_groups"
        description: |
          A logout attempt without a valid session will result in a `401 Unauthorized` error.

          A session that was not created due to a login cannot be deleted (e.g., empty API password).
        responses:
          '200':
            description: OK (session not deletable)
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: 'auth.yaml#/components/schemas/session'
                    - $ref: 'common.yaml#/components/schemas/took'
                examples:
                  no_login_required:
                    $ref: 'auth.yaml#/components/examples/no_login_required'
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: 'common.yaml#/components/errors/unauthorized'
                    - $ref: 'common.yaml#/components/schemas/took'
          '410':
            description: Gone
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: 'auth.yaml#/components/schemas/session'
                    - $ref: 'common.yaml#/components/schemas/took'
                examples:
                  login_failed:
                    $ref: 'auth.yaml#/components/examples/login_failed'
    session_list:
      get:
        summary: List of all current sessions
        tags:
          - Authentication
        operationId: "get_auth_sessions"
        description: List of all current sessions including their validity and further information about the client such as the IP address and user agent.
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: 'auth.yaml#/components/schemas/sessions_list'
                    - $ref: 'common.yaml#/components/schemas/took'
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: 'common.yaml#/components/errors/unauthorized'
                    - $ref: 'common.yaml#/components/schemas/took'
    totp:
      get:
        summary: Suggest new TOTP credentials
        tags:
          - Authentication
        operationId: "get_auth_totp"
        description: Suggest new TOTP credentials for two-factor authentication (2FA)
        responses:
          '200':
            description: OK
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: 'auth.yaml#/components/schemas/totp'
                    - $ref: 'common.yaml#/components/schemas/took'
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: 'common.yaml#/components/errors/unauthorized'
                    - $ref: 'common.yaml#/components/schemas/took'
    session:
      delete:
        summary: Delete session by ID
        parameters:
          - $ref: 'auth.yaml#/components/parameters/id'
        tags:
          - Authentication
        operationId: "delete_auth_session"
        description: |
          Using this endpoint, a session can be deleted by its ID.
        responses:
          '204':
            description: No Content (deleted)
          '400':
            description: Bad Request
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: 'auth.yaml#/components/errors/bad_request'
                    - $ref: 'common.yaml#/components/schemas/took'
                examples:
                  missing_session_id:
                    $ref: 'auth.yaml#/components/examples/errors/missing_session_id'
                  session_id_oob:
                    $ref: 'auth.yaml#/components/examples/errors/no_response'
                  session_not_in_use:
                    $ref: 'auth.yaml#/components/examples/errors/session_not_in_use'
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: 'common.yaml#/components/errors/unauthorized'
                    - $ref: 'common.yaml#/components/schemas/took'

  schemas:
    session:
      type: object
      required:
        - challenge
        - session
      properties:
        challenge:
          type: string
          description: Challenge to be used for computing response
          nullable: true
        session:
          type: object
          description: Session object
          required:
            - valid
            - sid
            - validity
            - totp
          properties:
            valid:
              type: boolean
              description: Valid session indicator (client is authenticated)
            totp:
              type: boolean
              description: Whether 2FA (TOTP) is enabled on this Pi-hole
            sid:
              type: string
              description: Session ID
              nullable: true
            validity:
              type: integer
              description: Remaining lifetime of this session unless refreshed (seconds)
        dns:
          type: boolean
          description: Whether the DNS server is up and running. False only in failed state

    response:
      type: object
      description: Response to be sent to the API
      properties:
        response:
          type: string
          description: Response to previous challenge
          example: abcdef
    sessions_list:
      type: object
      description: List of all current sessions
      properties:
        sessions:
          type: array
          items:
            type: object
            description: Session object
            properties:
              id:
                type: number
                description: Session ID
              current_session:
                type: boolean
                description: Indicator if this is the current session
              valid:
                type: boolean
                description: Valid session indicator (existing sessions may be invalid due to timeout)
              tls:
                type: object
                description: TLS (end-to-end encryption) information
                properties:
                  login:
                    type: boolean
                    description: Indicator if TLS (end-to-end encryption) has been used during login for this session
                  mixed:
                    type: boolean
                    description: Indicator if TLS (end-to-end encryption) is used only partially for this session
              login_at:
                type: integer
                description: Timestamp of login (seconds since epoch)
              last_active:
                type: integer
                description: Timestamp of last activity (seconds since epoch)
              valid_until:
                type: integer
                description: Timestamp of session expiration (seconds since epoch)
              remote_addr:
                type: string
                description: IP address of the client
              user_agent:
                type: string
                description: User agent of the client
          example:
            - id: 1
              current_session: true
              valid: true
              tls:
                login: true
                mixed: false
              strict_tls: false
              login_at: 1580000000
              last_active: 1580000000
              valid_until: 1580000300
              remote_addr: "192.168.0.34"
              user_agent: "Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0"
    totp:
      type: object
      description: TOTP secret suggestion
      properties:
        totp:
          type: object
          properties:
            type:
              type: string
            account:
              type: string
            issuer:
              type: string
            algorithm:
              type: string
            digits:
              type: integer
            period:
              type: integer
            offset:
              type: integer
            secret:
              type: string
            codes:
              type: array
              items:
                type: integer

  errors:
    bad_request:
      type: object
      description: Bad request
      properties:
        error:
          type: object
          properties:
            key:
              type: string
              description: "Machine-readable error type"
            message:
              type: string
              description: "Human-readable error message"
            hint:
              type: string
              description: "Additional data (if available)"
              nullable: true

  examples:
    login_okay:
      summary: Login successful
      value:
        challenge: null
        session:
          valid: true
          totp: false
          sid: null
          validity: 300
        dns: true
    no_login_required:
      summary: No login required for this client
      value:
        challenge: null
        session:
          valid: true
          totp: false
          sid: null
          validity: -1
        dns: true
    login_required:
      summary: Login required
      value:
        challenge: "a2926b025bcc8618c632f81cd6cf7c37ee051c08aab74b565fd5126350fcd056"
        session:
          valid: false
          totp: false
          sid: null
          validity: -1
        dns: true
    login_failed:
      summary: Login failed
      value:
        challenge: null
        session:
          valid: false
          totp: false
          sid: null
          validity: -1
        dns: true
    dns_failure:
      summary: DNS server failure
      value:
        challenge: "a2926b025bcc8618c632f81cd6cf7c37ee051c08aab74b565fd5126350fcd056"
        session:
          valid: false
          totp: false
          sid: null
          validity: -1
        dns: false
    errors:
      no_payload:
        summary: Bad request (no valid JSON payload)
        value:
          error:
            key: "bad_request"
            message: "No valid JSON payload found"
            hint: null
      no_response:
        summary: Bad request (no response)
        value:
          error:
            key: "bad_request"
            message: "No response found in JSON payload"
            hint: null
      response_inval:
        summary: Bad request (invalid response)
        value:
          error:
            key: "bad_request"
            message: "Invalid response length"
            hint: null
      missing_session_id:
        summary: Bad request (missing session ID)
        value:
          error:
            key: "bad_request"
            message: "Missing or invalid session ID"
            hint: null
      session_id_oob:
        summary: Bad request (session ID out of bounds)
        value:
          error:
            key: "bad_request"
            message: "Session ID out of bounds"
            hint: null
      session_not_in_use:
        summary: Bad request (session not in use)
        value:
          error:
            key: "bad_request"
            message: "Session ID not in use"
            hint: null
  parameters:
    id:
      in: path
      name: id
      schema:
        type: integer
      required: true
      description: Session ID
      example: 0
